config/routes.rb
Rails.application.routes.draw do
  resources :api_shortners
  root :to => 'api_shortners#index'
end

app/models/api_shortner.rb
class ApiShortner < ApplicationRecord
  after_create :generate_slug

  validates :input_url, :presence => true

  # generate the new unique slug and updates in the api shortner table
  def generate_slug
    self.slug = self.id.to_s(36)
    self.save
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/api_shortners_controller.rb
class ApiShortnersController < ApplicationController
  include ActionController::MimeResponds
  before_action :set_url, only: [:show]

  # response will be given in the form of html and js only
  respond_to :html, :js

  # Retrives the all the url's with number of clicks in desending order
  def index
    @api_shortner = ApiShortner.new
    @shortners = ApiShortner.all.order("num_of_clicks DESC")
  end

  # create the new url shorner based on the params
  def create
    @api_shortner = ApiShortner.create(shortner_params)
  end

  # create the new url shorner based on the params
  def show
    if redirect_to @api_shortner.first.input_url
        @api_shortner.first.num_of_clicks = 0 if @api_shortner.first.num_of_clicks.nil?
        @api_shortner.first.num_of_clicks += 1
        @api_shortner.first.save
      end
  end

  # private methods for params and setting the url shortner
  private
  def shortner_params
    params.require(:api_shortner).permit(:input_url, :slug, :num_of_clicks)
  end

  def set_url
    @api_shortner = ApiShortner.where(slug: params[:id])
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/helpers/api_shorners_helper.rb
module ApiShornersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/api_shortners/_form.html.erb
<%= form_for(@api_shortner, url: {controller: "api_shortners", action: "create"}, remote: true) do |f| %>
  <% if @api_shortner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@api_shortner.errors.count, "error") %> prohibited this link from being saved:</h2>
      <ul>
      <% @api_shortner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input-group">
    <%= f.text_field :input_url, :class => "form-control", :placeholder => "Shorten links" %>
    <span class="input-group-btn">
          <%= f.submit 'Shorten Me', :class => "btn btn-primary"%>
      </span
  </div>
<% end %>

app/views/api_shortners/create.js.erb
<% if @api_shortner.id.present? %>
  $('.shortner').append('<div class="col-lg-6"><div class="panel panel-default"><div class="panel-body"><p class="short_url"><%= link_to request.original_url + "/" + @api_shortner.slug, api_shortner_path(@api_shortner.slug), target: "_blank" %></p></div></div></div>')
<% end %>

app/views/api_shortners/index.html.erb
<div class="container">
  <div class="col-lg-12 ">
      <div class="panel panel-default">
        <div class="panel panel-title col-md-offset-4">
          <h1>All Shorten links</h1>
        </div>
        <div class="panel-body">
          <%= render 'api_shortners/form' %>
        </div>
    </div>
  </div>
</div>

<% @shortners.each do |shortner| %>
  <div class="col-lg-6">
      <div class="panel panel-default">
        <div class="panel-body">
            <p class="short_url"> <%= link_to request.original_url + "api_shortners/" + shortner.slug, api_shortner_path(shortner.slug), target: '_blank' %></p>
          </div
        </div>
    </div>
  </div>
<% end %>
<div class="shortner">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortenUrl</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>